# Generated by Django 4.1.4 on 2022-12-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_batch_students_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='students_json',
        ),
    ]
