# Generated by Django 4.1.4 on 2022-12-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_batch_students_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='semester_id',
        ),
        migrations.AddField(
            model_name='semester',
            name='batch_no',
            field=models.CharField(default='', max_length=8),
        ),
    ]
