# Generated by Django 4.1.4 on 2022-12-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_course_course_results_json_course_batch_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
    ]
