# Generated by Django 4.1.4 on 2022-12-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_course_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester_no',
            field=models.IntegerField(default=None),
        ),
    ]
