# Generated by Django 4.1.4 on 2022-12-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_course_semester_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester_no',
        ),
    ]
