# Generated by Django 4.1.4 on 2022-12-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_course_semester_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='courses_json',
        ),
    ]
