# Generated by Django 4.1.4 on 2022-12-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_semester_courses_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default='', max_length=10)),
                ('batch_no', models.CharField(default='', max_length=6)),
                ('semester_no', models.IntegerField(default=None)),
                ('part_a_decode', models.CharField(default='', max_length=10)),
                ('part_a_marks', models.IntegerField(default=None)),
                ('part_b_decode', models.CharField(default='', max_length=10)),
                ('part_b_marks', models.IntegerField(default=None)),
                ('assessment_marks', models.IntegerField(default=None)),
                ('total_marks', models.IntegerField(default=None)),
                ('GP', models.CharField(default='', max_length=5)),
                ('LG', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
