# Generated by Django 4.1.4 on 2022-12-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_courseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresult',
            name='course_code',
            field=models.CharField(default='', max_length=8),
        ),
    ]
