# Generated by Django 4.1.4 on 2022-12-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_courseresult_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionalCourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default='', max_length=10)),
                ('batch_no', models.CharField(default='', max_length=6)),
                ('semester_no', models.IntegerField(default=None)),
                ('course_code', models.CharField(default='', max_length=8)),
                ('lab_marks', models.IntegerField(default=None)),
                ('assessment_marks', models.IntegerField(default=None)),
                ('total_marks', models.IntegerField(default=None)),
                ('GP', models.CharField(default='', max_length=5)),
                ('LG', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='CourseResult',
            new_name='TheoryCourseResult',
        ),
    ]
