# Generated by Django 4.1.4 on 2022-12-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sessionalcourseresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(default='', max_length=10)),
                ('batch_no', models.CharField(default='', max_length=6)),
                ('semester_no', models.IntegerField(default=None)),
                ('course_results', models.CharField(default='', max_length=1000)),
                ('current_semester_credits', models.FloatField(default=0)),
                ('current_semester_total_GP', models.FloatField(default=0)),
                ('overall_credits', models.FloatField(default=0)),
                ('overall_GP', models.FloatField(default=0)),
            ],
        ),
    ]
