# Generated by Django 4.1.4 on 2023-01-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_result_delete_tablesheet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('designation', models.CharField(default='', max_length=60)),
                ('isGuest', models.BooleanField(default=False)),
            ],
        ),
    ]
