# Generated by Django 4.1.4 on 2023-01-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_teacher_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='isGuest',
        ),
        migrations.AddField(
            model_name='teacher',
            name='institute',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
