# Generated by Django 4.1.4 on 2023-01-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_teacher_isguest_teacher_institute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(default='', max_length=6)),
                ('semester_no', models.IntegerField(default=0)),
                ('course_code', models.CharField(default='', max_length=8)),
                ('tt_mode', models.CharField(default='', max_length=10)),
                ('tt_counting_on', models.IntegerField(default=0)),
                ('tt_results', models.CharField(default='', max_length=1000)),
                ('assignment_counting_on', models.IntegerField(default=0)),
                ('assignment_results', models.CharField(default='', max_length=1000)),
                ('attendance_counting_on', models.IntegerField(default=0)),
                ('total_classes', models.IntegerField(default=None)),
                ('attended_classes', models.CharField(default='', max_length=1000)),
                ('total_assessment_marks', models.IntegerField(default=0)),
            ],
        ),
    ]
