# Generated by Django 4.1.4 on 2023-01-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_assessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='num_of_assignment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='num_of_tt',
            field=models.IntegerField(default=0),
        ),
    ]
