# Generated by Django 4.1.4 on 2023-01-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_assessmentresult_num_of_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='total_assessment_marks',
        ),
    ]
