# Generated by Django 4.1.4 on 2023-01-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_assessmentresult_total_assessment_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='num_of_assignment',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='num_of_tt',
        ),
    ]
