# Generated by Django 4.1.4 on 2023-01-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_assessmentresult_num_of_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='attendance_counting_on',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='attended_classes',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='total_classes',
        ),
    ]
