# Generated by Django 4.1.4 on 2023-01-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_assessmentresult_attendance_counting_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='assignment_counting_on',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='tt_counting_on',
            field=models.IntegerField(default=20),
        ),
    ]
