# Generated by Django 4.1.4 on 2023-01-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_assessmentresult_assignment_counting_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='attendance_counting_on',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='attendance_results',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='tt_mode',
            field=models.CharField(default='average', max_length=10),
        ),
    ]
